name: Deploy Fly.io Backend

on:
  push:
    branches:
      - main
    paths:
      - 'fly/**'

jobs:
  deploy:
    name: Deploy Fly.io Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: ./fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}